analyzer:
  plugins:
    - custom_lint
  errors:
    constant_identifier_names: ignore
    invalid_annotation_target: ignore
    sort_pub_dependencies: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - avoid_relative_lib_imports
    - avoid_returning_null_for_void
    - avoid_types_as_parameter_names
    - avoid_unused_constructor_parameters
    - empty_constructor_bodies
    - prefer_adjacent_string_concatenation
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_final_locals
    - prefer_for_elements_to_map_fromIterable
    - prefer_if_elements_to_conditional_expressions
    - prefer_if_null_operators
    - prefer_is_not_empty
    - prefer_iterable_whereType
    - prefer_single_quotes
    - sort_pub_dependencies
    - unnecessary_brace_in_string_interps
    - unnecessary_new
    - unnecessary_this